blank_issues_enabled: false
contact_links:
  - name: ğŸ¤” Questions
    url: https://github.com/xelaj/mtproto/discussions
    about: Please ask and answer questions here.
  - name: Report a security vulnerability # ğŸ” Security issue
    url: https://github.com/xelaj/mtproto/blob/master/.github/SECURITY.md
    about: Please review our security policy for more details
  - name: ğŸ— Support
    url: https://github.com//xelaj/mtproto/blob/master/.github/SUPPORT.md
    about: Support this project without writing code
